require_relative("../models/screening")
require_relative("../models/ticket")
require_relative("../models/film")
require_relative("../models/customer")

require("pry")

Ticket.delete_all()
Screening.delete_all()
Film.delete_all()
Customer.delete_all()

customer1 = Customer.new({ "name" => "Hephestus", "funds" => 1000 })
customer2 = Customer.new({ "name" => "Malachi", "funds" => 2000 })
customer3 = Customer.new({ "name" => "Plutarch", "funds" => 3000 })
customer4 = Customer.new({ "name" => "Vigano", "funds" => 4000 })
customer5 = Customer.new({ "name" => "Torquemada", "funds" => 5000 })
customer6 = Customer.new({ "name" => "Derek", "funds" => 6000 })
customer7 = Customer.new({ "name" => "Azreal", "funds" => 7000 })
customer8 = Customer.new({ "name" => "Baphomet", "funds" => 8000 })
customer9 = Customer.new({ "name" => "Mollock", "funds" => 9000 })
customer10 = Customer.new({ "name" => "Yur the Obscure", "funds" => 10000 })
customer1.save()
customer2.save()
customer3.save()
customer4.save()
customer5.save()
customer6.save()
customer7.save()
customer8.save()
customer9.save()
customer10.save()

film1 = Film.new({ "title" => "Armitage Shanks Returns", "genre" => "comedy", "price" => 10 })
film2 = Film.new({ "title" => "One Man And His Flannel", "genre" => "comedy", "price" => 20 })
film3 = Film.new({ "title" => "Cheeky Chappy Misappropriates Penny-farthing", "genre" => "action", "price" => 30 })
film4 = Film.new({ "title" => "Brunching With Ferrets", "genre" => "horror", "price" => 40 })
film1.save()
film2.save()
film3.save()
film4.save()

ticket1 = Ticket.new({ "customer_id" => customer1.id, "film_id" => film1.id })
ticket2 = Ticket.new({ "customer_id" => customer2.id, "film_id" => film1.id })
ticket3 = Ticket.new({ "customer_id" => customer3.id, "film_id" => film2.id })
ticket4 = Ticket.new({ "customer_id" => customer4.id, "film_id" => film2.id })
ticket5 = Ticket.new({ "customer_id" => customer5.id, "film_id" => film3.id })
ticket6 = Ticket.new({ "customer_id" => customer6.id, "film_id" => film3.id })
ticket7 = Ticket.new({ "customer_id" => customer7.id, "film_id" => film1.id })
ticket8 = Ticket.new({ "customer_id" => customer8.id, "film_id" => film2.id })
ticket9 = Ticket.new({ "customer_id" => customer9.id, "film_id" => film3.id })
ticket10 = Ticket.new({ "customer_id" => customer10.id, "film_id" => film4.id })
ticket11 = Ticket.new({ "customer_id" => customer1.id, "film_id" => film2.id })
ticket12 = Ticket.new({ "customer_id" => customer1.id, "film_id" => film3.id })
ticket1.save()
ticket2.save()
ticket3.save()
ticket4.save()
ticket5.save()
ticket6.save()
ticket7.save()
ticket8.save()
ticket9.save()
ticket10.save()
ticket11.save()
ticket12.save()

screening1 = Screening.new({ "film_id" => film1.id, "time" => "01:00" })
screening2 = Screening.new({ "film_id" => film1.id, "time" => "02:00" })
screening3 = Screening.new({ "film_id" => film2.id, "time" => "03:00" })
screening4 = Screening.new({ "film_id" => film2.id, "time" => "04:00" })
screening5 = Screening.new({ "film_id" => film3.id, "time" => "05:00" })
screening6 = Screening.new({ "film_id" => film3.id, "time" => "06:00" })
screening7 = Screening.new({ "film_id" => film4.id, "time" => "07:00" })
screening8 = Screening.new({ "film_id" => film1.id, "time" => "02:00" })
screening9 = Screening.new({ "film_id" => film1.id, "time" => "03:00" })
screening10 = Screening.new({ "film_id" => film1.id, "time" => "04:00" })

screening1.save()
screening2.save()
screening3.save()
screening4.save()
screening5.save()
screening6.save()
screening7.save()
screening8.save()
screening9.save()
screening10.save()

binding.pry

nil
